# Generated by Django 5.2.17 on 2026-09-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='category',
            field=models.CharField(choices=[('men', "Men's"), ('women', "Women's"), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'duration_days'), name='unique_plan_product'),
        ),
    ]
