# Generated by Django 5.2.17 on 2026-09-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
